name: Terraform Lambda CI/CD

on:
  push:
    branches: [main]
    paths:
      - '*.tf'
      - 'lambda_layer/**'
      - '*.py'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Build Lambda layer
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy \
            --platform manylinux2014_x86_64 \
            --only-binary=:all: \
            --implementation cp \
            --python-version 3.9 \
            -t lambda_layer/python/
          cd lambda_layer && zip -r python_layer.zip python

      - run: terraform init
      - run: terraform apply -auto-approve
