name: Deploy Lambda with Terraform

on:
  push:
    branches: [main]
    paths:
      - 'lambda_function.py'
      - 'main.tf'
      - '.github/workflows/deploy_lambda.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Setear credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # o ${{ secrets.AWS_REGION }}

      - name: Crear ZIP para Lambda
        run: zip -j lambda_function_payload.zip lambda_function.py

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6  # Puedes cambiar la versión

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
